name: Multi shell command in one step
on: workflow_dispatch
jobs:
  multi-shell:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: |
           sudo apt-get update && sudo apt-get install -y ncal
           date
           cal
