name: Using secrets in yml file
on: workflow_dispatch
jobs:
  Job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Building application with secrets
        run: echo "Building the application with the following ${{ secrets.Docker_PASSWD }}"
